name: "Functionality tests"

on:
  push:

concurrency:
  group: ${{ github.head_ref }}-tests
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm install
    - name: Run tests
      run: npm test
